package main

import (
	"log"
	"merchant_back/internal/config"
	"merchant_back/internal/routes"

	_ "merchant_back/docs" // docs is generated by Swag CLI

	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

// @title Merchant Admin API
// @version 1.0
// @description 商家管理系统的后端API服务
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name MIT
// @license.url https://opensource.org/licenses/MIT

// @host localhost:8080
// @BasePath /api/v1

// @securityDefinitions.apikey BearerAuth
// @in header
// @name Authorization
// @description Type "Bearer" followed by a space and JWT token.

// @tag.name auth
// @description 认证相关接口

// @tag.name users
// @description 用户管理接口

// main 应用程序入口点
// @description 初始化配置、数据库连接、服务和路由，启动HTTP服务器
func main() {
	// 加载配置
	cfg := config.LoadConfig()

	// 设置 Gin 模式
	gin.SetMode(cfg.Server.Mode)

	// 初始化数据库
	InitDB()
	defer CloseDB()

	// 使用路由配置，SetupRoutes 函数内部会创建所需的服务和控制器
	r := routes.SetupRoutes(DB)

	// 添加 Swagger 路由
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// 启动服务器
	log.Printf("Server starting on port %s", cfg.Server.Port)
	log.Printf("Swagger documentation available at: http://localhost:%s/swagger/index.html", cfg.Server.Port)
	if err := r.Run(":" + cfg.Server.Port); err != nil {
		log.Fatal("Failed to start server: ", err)
	}
}
